### ISSUE TITLE
Does this work only for pages in master?

### ISSUE THREAD

**Issue by ocefpaf** [David-Byrne/jekyll-diff-action#6]
If I understood the `jekyll_diff.sh` the comparison happens against the `master` and not the target branch of the PR, right? If not I'm probably misusing it and feel free to close this.

If that is correct I believe that using the target branch would make this action more useful.

**Comment by David-Byrne** [comment]
Nice catch, comparing against the target branch would make much more sense alright

**Comment by David-Byrne** [comment]
Fixed in #7

**Comment by ocefpaf** [comment]
Thanks!
